import { P, RECIPE, USDA, n, type SeedFood } from './shared.js';

/**
 * Đồ uống, sữa, chè and the snacks.
 *
 * Sweetened Vietnamese drinks are the least certain category in the dataset: how much
 * condensed milk goes into a cà phê sữa đá is entirely up to the person making it, so
 * several of these are honestly `low`.
 */
export const DRINKS_AND_SNACKS: SeedFood[] = [
  // ── Đồ uống ───────────────────────────────────────────────────────────────
  {
    externalId: 'vn-nuoc-loc',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Nước lọc',
    nameEn: 'Water',
    category: 'drink',
    per100g: n(0, 0, 0, 0, 0),
    dataQuality: 'high',
    sourceReference: 'Water contains no macronutrients; logged for hydration rather than energy',
    portions: P.drink(),
  },
  {
    externalId: 'vn-tra-da',
    nameVi: 'Trà đá',
    nameEn: 'Iced tea, unsweetened',
    category: 'drink',
    per100g: n(1, 0, 0.3, 0, 0),
    dataQuality: 'high',
    sourceReference: USDA('tea, brewed, unsweetened'),
    portions: P.drink(),
  },
  {
    externalId: 'vn-ca-phe-den',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Cà phê đen',
    nameEn: 'Black coffee, no sugar',
    category: 'drink',
    per100g: n(2, 0.2, 0.3, 0, 0),
    dataQuality: 'high',
    sourceReference: USDA('coffee, brewed, unsweetened'),
    portions: [{ label: '1 cup', labelVi: '1 ly', grams: 120, isDefault: true }],
  },
  {
    externalId: 'vn-ca-phe-sua-da',
    nameVi: 'Cà phê sữa đá',
    nameEn: 'Iced coffee with condensed milk',
    category: 'drink',
    per100g: n(78, 1.6, 13.4, 2.2, 0),
    dataQuality: 'low',
    sourceReference: RECIPE(
      '25 g sweetened condensed milk in strong coffee over ice; the milk quantity is entirely at the maker discretion, so this is indicative only',
    ),
    portions: [{ label: '1 glass', labelVi: '1 ly', grams: 200, isDefault: true }],
  },
  {
    externalId: 'vn-bac-xiu',
    nameVi: 'Bạc xỉu',
    nameEn: 'Iced milk coffee, milk-forward',
    category: 'drink',
    per100g: n(96, 2.2, 16.0, 2.8, 0),
    dataQuality: 'low',
    sourceReference: RECIPE('as cà phê sữa đá with more condensed milk and less coffee'),
    portions: [{ label: '1 glass', labelVi: '1 ly', grams: 200, isDefault: true }],
  },
  {
    externalId: 'vn-tra-sua',
    nameVi: 'Trà sữa',
    nameEn: 'Milk tea with tapioca pearls',
    category: 'drink',
    per100g: n(88, 1.1, 17.4, 1.8, 0.2),
    dataQuality: 'low',
    sourceReference: RECIPE(
      'black tea with milk powder, sugar syrup and tapioca pearls; sugar level is chosen per order, so the same drink ranges widely and this is indicative only',
    ),
    portions: [
      { label: '1 cup', labelVi: '1 ly', grams: 350, isDefault: true },
      { label: 'large cup', labelVi: 'ly lớn', grams: 500 },
    ],
  },
  {
    externalId: 'vn-nuoc-mia',
    nameVi: 'Nước mía',
    nameEn: 'Sugarcane juice',
    category: 'drink',
    per100g: n(58, 0.1, 14.6, 0.1, 0.1),
    dataQuality: 'medium',
    sourceReference: RECIPE('pressed sugarcane juice; essentially sucrose in water, concentration varies with the cane'),
    portions: [{ label: '1 glass', labelVi: '1 ly', grams: 300, isDefault: true }],
  },
  {
    externalId: 'vn-nuoc-cam',
    nameVi: 'Nước cam',
    nameEn: 'Orange juice, fresh',
    category: 'drink',
    per100g: n(45, 0.7, 10.4, 0.2, 0.2),
    dataQuality: 'high',
    sourceReference: USDA('orange juice, raw'),
    portions: P.drink(),
  },
  {
    externalId: 'vn-sinh-to-bo',
    nameVi: 'Sinh tố bơ',
    nameEn: 'Avocado smoothie',
    category: 'drink',
    per100g: n(122, 1.8, 13.2, 7.2, 2.4),
    dataQuality: 'medium',
    sourceReference: RECIPE('avocado blended with condensed milk and ice'),
    portions: [{ label: '1 glass', labelVi: '1 ly', grams: 300, isDefault: true }],
  },
  {
    externalId: 'vn-nuoc-dua',
    nameVi: 'Nước dừa',
    nameEn: 'Coconut water',
    category: 'drink',
    per100g: n(19, 0.7, 3.7, 0.2, 1.1),
    dataQuality: 'high',
    sourceReference: USDA('nuts, coconut water'),
    portions: [{ label: '1 coconut', labelVi: '1 trái', grams: 350, isDefault: true }],
  },
  {
    externalId: 'vn-bia',
    nameVi: 'Bia',
    nameEn: 'Beer, regular',
    category: 'drink',
    per100g: n(43, 0.5, 3.6, 0, 0),
    dataQuality: 'high',
    sourceReference: USDA('beer, regular, around 4.5% ABV'),
    portions: [
      { label: '1 can', labelVi: '1 lon', grams: 330, isDefault: true },
      { label: '1 bottle', labelVi: '1 chai', grams: 500 },
    ],
  },

  // ── Sữa & chế phẩm ────────────────────────────────────────────────────────
  {
    externalId: 'vn-sua-tuoi',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Sữa tươi',
    nameEn: 'Whole milk',
    category: 'dairy',
    per100g: n(61, 3.2, 4.8, 3.3, 0),
    dataQuality: 'high',
    sourceReference: USDA('milk, whole, 3.25% fat'),
    portions: [
      { label: '1 glass', labelVi: '1 ly', grams: 240, isDefault: true },
      { label: '1 carton', labelVi: '1 hộp', grams: 180 },
    ],
  },
  {
    externalId: 'vn-sua-tuoi-khong-duong',
    nameVi: 'Sữa tươi không đường',
    nameEn: 'Unsweetened fresh milk',
    category: 'dairy',
    per100g: n(60, 3.3, 4.6, 3.2, 0),
    dataQuality: 'high',
    sourceReference: USDA('milk, whole, unsweetened'),
    portions: [{ label: '1 carton', labelVi: '1 hộp', grams: 180, isDefault: true }],
  },
  {
    externalId: 'vn-sua-dac',
    nameVi: 'Sữa đặc',
    nameEn: 'Sweetened condensed milk',
    category: 'dairy',
    per100g: n(321, 7.9, 54.4, 8.7, 0),
    dataQuality: 'high',
    sourceReference: USDA('milk, condensed, sweetened'),
    portions: [{ label: '1 tablespoon', labelVi: '1 muỗng canh', grams: 20, isDefault: true }],
  },
  {
    externalId: 'vn-sua-chua',
    nameVi: 'Sữa chua',
    nameEn: 'Sweetened yoghurt',
    category: 'dairy',
    per100g: n(97, 3.5, 15.7, 2.5, 0),
    dataQuality: 'medium',
    sourceReference: RECIPE('Vietnamese-style set yoghurt made with condensed milk, sweeter than plain yoghurt'),
    portions: [{ label: '1 pot', labelVi: '1 hũ', grams: 100, isDefault: true }],
  },
  {
    externalId: 'vn-sua-dau-nanh',
    nameVi: 'Sữa đậu nành',
    nameEn: 'Soy milk, sweetened',
    category: 'drink',
    per100g: n(54, 3.3, 6.0, 1.8, 0.5),
    dataQuality: 'medium',
    sourceReference: RECIPE('home-style sweetened soy milk'),
    portions: P.drink(),
  },
  {
    externalId: 'vn-pho-mai',
    nameVi: 'Phô mai',
    nameEn: 'Processed cheese',
    category: 'dairy',
    per100g: n(300, 18.0, 5.0, 23.0, 0),
    dataQuality: 'medium',
    sourceReference: RECIPE('processed cheese wedge, as commonly sold in Vietnam'),
    portions: [{ label: '1 wedge', labelVi: '1 miếng', grams: 15, isDefault: true }],
  },

  // ── Chè & bánh ngọt ───────────────────────────────────────────────────────
  {
    externalId: 'vn-che-dau-xanh',
    nameVi: 'Chè đậu xanh',
    nameEn: 'Mung bean sweet soup',
    category: 'snack',
    per100g: n(118, 3.2, 24.0, 1.2, 1.8),
    dataQuality: 'medium',
    sourceReference: RECIPE('mung bean cooked with sugar and a little coconut milk'),
    portions: [{ label: '1 cup', labelVi: '1 ly', grams: 200, isDefault: true }],
  },
  {
    externalId: 'vn-che-ba-mau',
    nameVi: 'Chè ba màu',
    nameEn: 'Three-colour sweet soup',
    category: 'snack',
    per100g: n(142, 2.4, 26.0, 3.6, 1.6),
    dataQuality: 'medium',
    sourceReference: RECIPE('mung bean, red bean and pandan jelly with coconut milk and ice'),
    portions: [{ label: '1 cup', labelVi: '1 ly', grams: 250, isDefault: true }],
  },
  {
    externalId: 'vn-banh-flan',
    nameVi: 'Bánh flan',
    nameEn: 'Caramel custard',
    category: 'snack',
    per100g: n(154, 4.6, 21.0, 5.8, 0),
    dataQuality: 'medium',
    sourceReference: RECIPE('egg and condensed milk custard with caramel'),
    portions: [{ label: '1 pot', labelVi: '1 hũ', grams: 100, isDefault: true }],
  },
  {
    externalId: 'vn-banh-mi-ngot',
    nameVi: 'Bánh mì ngọt',
    nameEn: 'Sweet bread roll',
    category: 'snack',
    per100g: n(310, 8.0, 52.0, 8.0, 1.6),
    dataQuality: 'medium',
    sourceReference: RECIPE('enriched sweet bread roll'),
    portions: P.piece(60, '1 cái'),
  },
  {
    externalId: 'vn-banh-quy',
    nameVi: 'Bánh quy',
    nameEn: 'Biscuits',
    category: 'snack',
    per100g: n(480, 6.0, 66.0, 21.0, 2.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('typical sweet wheat biscuit'),
    portions: [{ label: '1 biscuit', labelVi: '1 cái', grams: 12, isDefault: true }],
  },
  {
    externalId: 'vn-khoai-mi-hap',
    nameVi: 'Khoai mì hấp',
    nameEn: 'Steamed cassava',
    category: 'snack',
    per100g: n(160, 1.4, 38.1, 0.3, 1.8),
    dataQuality: 'high',
    sourceReference: USDA('cassava, cooked'),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 150, isDefault: true }],
  },
  {
    externalId: 'vn-bap-luoc',
    nameVi: 'Bắp luộc',
    nameEn: 'Boiled sweetcorn',
    category: 'snack',
    per100g: n(96, 3.4, 21.0, 1.5, 2.4),
    dataQuality: 'high',
    sourceReference: USDA('corn, sweet, yellow, boiled'),
    portions: [{ label: '1 cob', labelVi: '1 trái', grams: 150, isDefault: true }],
  },

  // ── Gia vị & nước chấm ────────────────────────────────────────────────────
  {
    externalId: 'vn-nuoc-mam',
    nameVi: 'Nước mắm',
    nameEn: 'Fish sauce',
    category: 'condiment',
    per100g: n(35, 5.1, 3.6, 0, 0),
    dataQuality: 'high',
    sourceReference: USDA('fish sauce, ready to serve'),
    portions: [{ label: '1 tablespoon', labelVi: '1 muỗng canh', grams: 15, isDefault: true }],
  },
  {
    externalId: 'vn-nuoc-cham',
    nameVi: 'Nước chấm',
    nameEn: 'Diluted dipping fish sauce',
    category: 'condiment',
    per100g: n(62, 1.2, 14.0, 0, 0),
    dataQuality: 'medium',
    sourceReference: RECIPE('fish sauce diluted with water, sugar, lime, garlic and chilli'),
    portions: [{ label: '1 small bowl', labelVi: '1 chén nhỏ', grams: 30, isDefault: true }],
  },
  {
    externalId: 'vn-tuong-ot',
    nameVi: 'Tương ớt',
    nameEn: 'Chilli sauce',
    category: 'condiment',
    per100g: n(93, 1.0, 21.0, 0.4, 1.4),
    dataQuality: 'medium',
    sourceReference: RECIPE('sweet chilli sauce as commonly bottled in Vietnam'),
    portions: [{ label: '1 teaspoon', labelVi: '1 muỗng cà phê', grams: 6, isDefault: true }],
  },
  {
    externalId: 'vn-mam-tom',
    nameVi: 'Mắm tôm',
    nameEn: 'Fermented shrimp paste',
    category: 'condiment',
    per100g: n(85, 12.0, 4.0, 2.2, 0),
    dataQuality: 'low',
    sourceReference: RECIPE('fermented shrimp paste; composition varies widely by producer'),
    portions: [{ label: '1 tablespoon', labelVi: '1 muỗng canh', grams: 15, isDefault: true }],
  },
  {
    externalId: 'vn-dau-an',
    nameVi: 'Dầu ăn',
    nameEn: 'Cooking oil',
    category: 'condiment',
    per100g: n(884, 0, 0, 100, 0),
    dataQuality: 'high',
    sourceReference: USDA('vegetable oil'),
    portions: [{ label: '1 tablespoon', labelVi: '1 muỗng canh', grams: 14, isDefault: true }],
  },
  {
    externalId: 'vn-duong',
    nameVi: 'Đường',
    nameEn: 'Granulated sugar',
    category: 'condiment',
    per100g: n(387, 0, 100, 0, 0),
    dataQuality: 'high',
    sourceReference: USDA('sugars, granulated'),
    portions: [{ label: '1 teaspoon', labelVi: '1 muỗng cà phê', grams: 4, isDefault: true }],
  },
];
