import { P, RECIPE, USDA, n, type SeedFood } from './shared.js';

/**
 * The rest of the weekday rotation: everyday stir-fries and braises, more breakfast
 * items, and the international foods people in Vietnamese cities log alongside them.
 *
 * A tracker that only knows Vietnamese dishes fails the moment someone has a sandwich,
 * and one that only knows Western foods was the problem this dataset exists to solve.
 */
export const HOME_DISHES: SeedFood[] = [
  // ── Everyday stir-fries and braises ───────────────────────────────────────
  {
    externalId: 'vn-thit-bo-xao-hanh-tay',
    nameVi: 'Thịt bò xào hành tây',
    nameEn: 'Beef stir-fried with onion',
    category: 'meat',
    per100g: n(178, 17.4, 5.2, 9.6, 0.8),
    dataQuality: 'medium',
    sourceReference: RECIPE('beef sirloin stir-fried with onion in 6 g oil per 100 g finished dish'),
    portions: P.mainDish(150),
  },
  {
    externalId: 'vn-thit-bo-xao-rau-cu',
    nameVi: 'Thịt bò xào rau củ',
    nameEn: 'Beef stir-fried with mixed vegetables',
    category: 'meat',
    per100g: n(146, 13.8, 6.4, 7.4, 1.4),
    dataQuality: 'medium',
    sourceReference: RECIPE('beef with broccoli, carrot and pepper, stir-fried in 5 g oil per 100 g'),
    portions: P.mainDish(180),
  },
  {
    externalId: 'vn-thit-heo-xao-sa-ot',
    nameVi: 'Thịt heo xào sả ớt',
    nameEn: 'Pork stir-fried with lemongrass and chilli',
    category: 'meat',
    per100g: n(212, 18.2, 4.8, 13.6, 0.7),
    dataQuality: 'medium',
    sourceReference: RECIPE('pork shoulder stir-fried with lemongrass, chilli and fish sauce'),
    portions: P.mainDish(150),
  },
  {
    externalId: 'vn-ga-xao-sa-ot',
    nameVi: 'Gà xào sả ớt',
    nameEn: 'Chicken stir-fried with lemongrass and chilli',
    category: 'meat',
    per100g: n(176, 19.6, 4.4, 9.0, 0.7),
    dataQuality: 'medium',
    sourceReference: RECIPE('chicken thigh stir-fried with lemongrass and chilli in 5 g oil per 100 g'),
    portions: P.mainDish(150),
  },
  {
    externalId: 'vn-ga-chien-nuoc-mam',
    nameVi: 'Gà chiên nước mắm',
    nameEn: 'Fish sauce fried chicken wings',
    category: 'meat',
    per100g: n(268, 20.4, 8.6, 17.2, 0.2),
    dataQuality: 'medium',
    sourceReference: RECIPE('chicken wings deep fried then tossed in reduced fish sauce and sugar'),
    portions: P.mainDish(120),
  },
  {
    externalId: 'vn-ga-ran',
    nameVi: 'Gà rán',
    nameEn: 'Fried chicken, battered',
    category: 'meat',
    per100g: n(285, 20.0, 14.0, 16.8, 0.8),
    dataQuality: 'medium',
    sourceReference: RECIPE('battered and deep-fried chicken, fast-food style'),
    portions: P.piece(110, '1 miếng'),
  },
  {
    externalId: 'vn-com-ga',
    nameVi: 'Cơm gà',
    nameEn: 'Chicken rice',
    category: 'rice_grain',
    per100g: n(168, 9.2, 24.0, 3.8, 0.5),
    dataQuality: 'medium',
    sourceReference: RECIPE('rice cooked in chicken stock with poached chicken and herbs'),
    portions: [{ label: '1 plate', labelVi: '1 đĩa', grams: 380, isDefault: true }],
  },
  {
    externalId: 'vn-com-suon-nuong',
    nameVi: 'Cơm sườn nướng',
    nameEn: 'Rice with grilled pork chop',
    category: 'rice_grain',
    per100g: n(182, 9.0, 23.4, 6.0, 0.5),
    dataQuality: 'medium',
    sourceReference: RECIPE('250 g steamed rice with a 90 g grilled marinated pork chop and pickles'),
    portions: [{ label: '1 plate', labelVi: '1 đĩa', grams: 380, isDefault: true }],
  },
  {
    externalId: 'vn-ca-chien',
    nameVi: 'Cá chiên',
    nameEn: 'Pan-fried fish',
    category: 'seafood',
    per100g: n(196, 21.0, 1.2, 11.8, 0.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('white fish fillet shallow fried in 6 g oil per 100 g'),
    portions: P.mainDish(120),
  },
  {
    externalId: 'vn-ca-hap-gung',
    nameVi: 'Cá hấp gừng',
    nameEn: 'Steamed fish with ginger',
    category: 'seafood',
    per100g: n(126, 20.2, 1.8, 4.2, 0.2),
    dataQuality: 'medium',
    sourceReference: RECIPE('whole fish steamed with ginger, scallion and soy'),
    portions: P.mainDish(150),
  },
  {
    externalId: 'vn-tom-hap',
    nameVi: 'Tôm hấp',
    nameEn: 'Steamed prawns',
    category: 'seafood',
    per100g: n(102, 21.2, 0.4, 1.3, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('shrimp, steamed'),
    portions: P.mainDish(120),
  },
  {
    externalId: 'vn-muc-xao',
    nameVi: 'Mực xào',
    nameEn: 'Stir-fried squid with vegetables',
    category: 'seafood',
    per100g: n(148, 16.2, 6.2, 6.4, 0.9),
    dataQuality: 'medium',
    sourceReference: RECIPE('squid stir-fried with celery, onion and pepper in 5 g oil per 100 g'),
    portions: P.mainDish(150),
  },
  {
    externalId: 'vn-trung-kho-thit',
    nameVi: 'Trứng kho thịt',
    nameEn: 'Eggs braised with pork',
    category: 'egg',
    per100g: n(198, 13.6, 4.6, 14.2, 0.1),
    dataQuality: 'medium',
    sourceReference: RECIPE('hard-boiled eggs braised in the thịt kho liquor'),
    portions: P.mainDish(120),
  },
  {
    externalId: 'vn-trung-hap',
    nameVi: 'Trứng hấp',
    nameEn: 'Steamed egg custard with pork',
    category: 'egg',
    per100g: n(146, 11.8, 2.4, 10.0, 0.2),
    dataQuality: 'medium',
    sourceReference: RECIPE('beaten egg steamed with minced pork, wood ear and glass noodle'),
    portions: P.mainDish(150),
  },
  {
    externalId: 'vn-thit-luoc',
    nameVi: 'Thịt luộc',
    nameEn: 'Boiled pork belly, sliced',
    category: 'meat',
    per100g: n(298, 20.4, 0.0, 24.0, 0.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('pork belly simmered and sliced; leaner than fried, fattier than loin'),
    portions: [{ label: '1 slice', labelVi: '1 lát', grams: 25, isDefault: true }],
  },
  {
    externalId: 'vn-thit-quay',
    nameVi: 'Thịt quay',
    nameEn: 'Roast pork belly with crackling',
    category: 'meat',
    per100g: n(398, 19.0, 1.0, 35.4, 0.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('pork belly roasted to crisp skin'),
    portions: P.mainDish(100),
  },
  {
    externalId: 'vn-vit-quay',
    nameVi: 'Vịt quay',
    nameEn: 'Roast duck',
    category: 'meat',
    per100g: n(337, 19.0, 0.0, 28.4, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('duck, roasted, meat and skin'),
    portions: P.mainDish(120),
  },
  {
    externalId: 'vn-bo-kho',
    nameVi: 'Bò kho',
    nameEn: 'Beef stew with carrot and lemongrass',
    category: 'meat',
    per100g: n(126, 11.4, 5.8, 6.2, 0.9),
    dataQuality: 'medium',
    sourceReference: RECIPE('beef brisket stewed with carrot, lemongrass and annatto'),
    portions: [{ label: '1 bowl', labelVi: '1 tô', grams: 300, isDefault: true }],
  },
  {
    externalId: 'vn-ca-ri-ga',
    nameVi: 'Cà ri gà',
    nameEn: 'Vietnamese chicken curry',
    category: 'meat',
    per100g: n(142, 10.8, 8.4, 7.6, 1.2),
    dataQuality: 'medium',
    sourceReference: RECIPE('chicken and sweet potato in a coconut milk curry'),
    portions: [{ label: '1 bowl', labelVi: '1 tô', grams: 300, isDefault: true }],
  },

  // ── More rau and canh ─────────────────────────────────────────────────────
  {
    externalId: 'vn-dau-que-xao',
    nameVi: 'Đậu que xào',
    nameEn: 'Stir-fried green beans',
    category: 'vegetable',
    per100g: n(80, 2.2, 8.0, 4.6, 3.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('green beans stir-fried with garlic in 4 g oil per 100 g'),
    portions: P.vegetable(),
  },
  {
    externalId: 'vn-bong-cai-luoc',
    nameVi: 'Bông cải luộc',
    nameEn: 'Boiled broccoli',
    category: 'vegetable',
    per100g: n(35, 2.4, 7.2, 0.4, 3.3),
    dataQuality: 'high',
    sourceReference: USDA('broccoli, boiled, drained'),
    portions: P.vegetable(),
  },
  {
    externalId: 'vn-bi-do-ham',
    nameVi: 'Bí đỏ hầm',
    nameEn: 'Stewed pumpkin',
    category: 'vegetable',
    per100g: n(46, 1.4, 9.4, 0.6, 1.4),
    dataQuality: 'medium',
    sourceReference: RECIPE('pumpkin stewed with a little pork and stock'),
    portions: P.vegetable(),
  },
  {
    externalId: 'vn-rau-song',
    nameVi: 'Rau sống',
    nameEn: 'Fresh herb and lettuce plate',
    category: 'vegetable',
    per100g: n(18, 1.4, 3.0, 0.2, 1.8),
    dataQuality: 'medium',
    sourceReference: RECIPE('mixed raw herbs, lettuce and bean sprouts served alongside noodle dishes'),
    portions: P.vegetable(),
  },
  {
    externalId: 'vn-canh-ca-chua-trung',
    nameVi: 'Canh cà chua trứng',
    nameEn: 'Tomato and egg soup',
    category: 'soup',
    per100g: n(38, 2.4, 2.8, 2.0, 0.5),
    dataQuality: 'medium',
    sourceReference: RECIPE('tomato simmered with beaten egg in a light broth'),
    portions: P.soup(),
  },
  {
    externalId: 'vn-canh-nghieu',
    nameVi: 'Canh nghêu',
    nameEn: 'Clam soup',
    category: 'soup',
    per100g: n(32, 4.0, 2.0, 0.7, 0.3),
    dataQuality: 'medium',
    sourceReference: RECIPE('clams simmered with pineapple and dill in a clear broth'),
    portions: P.soup(),
  },
  {
    externalId: 'vn-sup-cua',
    nameVi: 'Súp cua',
    nameEn: 'Crab and sweetcorn thick soup',
    category: 'soup',
    per100g: n(62, 4.2, 8.2, 1.4, 0.4),
    dataQuality: 'medium',
    sourceReference: RECIPE('crab meat, sweetcorn and egg white thickened with tapioca starch'),
    portions: [{ label: '1 bowl', labelVi: '1 chén', grams: 250, isDefault: true }],
  },

  // ── More breakfast and street food ────────────────────────────────────────
  {
    externalId: 'vn-banh-mi-op-la',
    nameVi: 'Bánh mì ốp la',
    nameEn: 'Baguette with pan-fried eggs',
    category: 'breakfast',
    per100g: n(240, 10.4, 30.0, 9.2, 1.7),
    dataQuality: 'medium',
    sourceReference: RECIPE('baguette served with two pan-fried eggs, pâté and soy'),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 220, isDefault: true }],
  },
  {
    externalId: 'vn-pho-mai-que',
    nameVi: 'Phở cuốn',
    nameEn: 'Rolled fresh pho sheets with beef',
    category: 'street_food',
    per100g: n(138, 8.4, 18.0, 3.4, 0.9),
    dataQuality: 'medium',
    sourceReference: RECIPE('fresh pho noodle sheets rolled around stir-fried beef and herbs'),
    portions: P.piece(50, '1 cuốn'),
  },
  {
    externalId: 'vn-banh-uot',
    nameVi: 'Bánh ướt',
    nameEn: 'Plain steamed rice sheets',
    category: 'breakfast',
    per100g: n(122, 3.0, 23.0, 1.8, 0.6),
    dataQuality: 'medium',
    sourceReference: RECIPE('steamed rice batter sheets with fried shallot and nước chấm'),
    portions: [{ label: '1 plate', labelVi: '1 đĩa', grams: 200, isDefault: true }],
  },
  {
    externalId: 'vn-hoanh-thanh-chien',
    nameVi: 'Hoành thánh chiên',
    nameEn: 'Fried wontons',
    category: 'street_food',
    per100g: n(302, 10.0, 28.0, 17.0, 1.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('pork and prawn wontons, deep fried'),
    portions: P.piece(20, '1 cái'),
  },
  {
    externalId: 'vn-oc-luoc',
    nameVi: 'Ốc luộc',
    nameEn: 'Boiled sea snails',
    category: 'seafood',
    per100g: n(90, 15.2, 4.4, 1.2, 0.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('sea snails boiled with lemongrass and lime leaf; edible portion only'),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 120, isDefault: true }],
  },
  {
    externalId: 'vn-banh-trang-tron',
    nameVi: 'Bánh tráng trộn',
    nameEn: 'Rice paper salad',
    category: 'snack',
    per100g: n(268, 8.4, 38.0, 9.4, 2.0),
    dataQuality: 'low',
    sourceReference: RECIPE(
      'shredded rice paper with dried beef, quail egg, peanut, herbs and satay oil; every vendor mixes it differently',
    ),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 150, isDefault: true }],
  },

  // ── International staples people also log ─────────────────────────────────
  {
    externalId: 'vn-yen-mach',
    nameVi: 'Yến mạch',
    nameEn: 'Porridge oats, cooked',
    category: 'rice_grain',
    per100g: n(71, 2.5, 12.0, 1.5, 1.7),
    dataQuality: 'high',
    sourceReference: USDA('oats, cooked with water'),
    portions: [{ label: '1 bowl', labelVi: '1 chén', grams: 250, isDefault: true }],
  },
  {
    externalId: 'vn-banh-mi-sandwich',
    nameVi: 'Bánh mì sandwich',
    nameEn: 'Sliced sandwich bread',
    category: 'bread',
    per100g: n(265, 9.0, 49.0, 3.2, 2.7),
    dataQuality: 'high',
    sourceReference: USDA('bread, white, commercially prepared'),
    portions: [{ label: '1 slice', labelVi: '1 lát', grams: 28, isDefault: true }],
  },
  {
    externalId: 'vn-mi-y',
    nameVi: 'Mì Ý',
    nameEn: 'Spaghetti with tomato sauce',
    category: 'noodle_dry',
    per100g: n(148, 5.4, 22.0, 4.2, 1.9),
    dataQuality: 'medium',
    sourceReference: RECIPE('cooked spaghetti with tomato and minced beef sauce'),
    portions: [{ label: '1 plate', labelVi: '1 đĩa', grams: 300, isDefault: true }],
  },
  {
    externalId: 'vn-pizza',
    nameVi: 'Pizza',
    nameEn: 'Pizza, cheese and topping',
    category: 'snack',
    per100g: n(266, 11.0, 33.0, 10.0, 2.3),
    dataQuality: 'medium',
    sourceReference: RECIPE('regular-crust cheese pizza with a meat topping'),
    portions: [{ label: '1 slice', labelVi: '1 miếng', grams: 100, isDefault: true }],
  },
  {
    externalId: 'vn-hamburger',
    nameVi: 'Hamburger',
    nameEn: 'Beef hamburger',
    category: 'snack',
    per100g: n(254, 13.0, 26.0, 11.0, 1.4),
    dataQuality: 'medium',
    sourceReference: RECIPE('fast-food beef burger with bun, sauce and salad'),
    portions: P.piece(200, '1 cái'),
  },
  {
    externalId: 'vn-ca-ngu-hop',
    nameVi: 'Cá ngừ hộp',
    nameEn: 'Canned tuna in water, drained',
    category: 'seafood',
    per100g: n(116, 25.5, 0.0, 0.8, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('tuna, light, canned in water, drained'),
    portions: [{ label: '1 can', labelVi: '1 hộp', grams: 140, isDefault: true }],
  },
  {
    externalId: 'vn-sua-chua-uong',
    nameVi: 'Sữa chua uống',
    nameEn: 'Drinking yoghurt',
    category: 'dairy',
    per100g: n(72, 2.4, 13.4, 1.0, 0.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('sweetened drinking yoghurt as commonly bottled'),
    portions: [{ label: '1 bottle', labelVi: '1 chai', grams: 180, isDefault: true }],
  },
  {
    externalId: 'vn-nuoc-ngot',
    nameVi: 'Nước ngọt',
    nameEn: 'Sweetened soft drink',
    category: 'drink',
    per100g: n(42, 0.0, 10.6, 0.0, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('carbonated cola beverage'),
    portions: [
      { label: '1 can', labelVi: '1 lon', grams: 330, isDefault: true },
      { label: '1 bottle', labelVi: '1 chai', grams: 500 },
    ],
  },
  {
    externalId: 'vn-nuoc-tang-luc',
    nameVi: 'Nước tăng lực',
    nameEn: 'Energy drink',
    category: 'drink',
    per100g: n(45, 0.0, 11.0, 0.0, 0.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('sweetened caffeinated energy drink'),
    portions: [{ label: '1 can', labelVi: '1 lon', grams: 250, isDefault: true }],
  },
];
