import { P, RECIPE, n, type SeedFood } from './shared.js';

/**
 * Món nước and the dry noodle dishes — what most people log for breakfast and lunch.
 *
 * Per-100g figures are for the *served bowl*, broth included. A tô of phở is mostly
 * liquid, so its per-100g energy is low while the bowl total is substantial; expressing
 * it any other way would make the portion arithmetic wrong.
 */
export const NOODLE_DISHES: SeedFood[] = [
  {
    externalId: 'vn-pho-bo',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Phở bò',
    nameEn: 'Beef noodle soup',
    category: 'noodle_soup',
    per100g: n(74, 4.6, 9.4, 1.9, 0.4),
    dataQuality: 'medium',
    sourceReference: RECIPE(
      '180 g cooked rice noodles, 70 g lean beef, 300 ml bone broth and herbs, per 100 g of the served bowl',
    ),
    portions: P.noodleSoup(),
  },
  {
    externalId: 'vn-pho-ga',
    nameVi: 'Phở gà',
    nameEn: 'Chicken noodle soup',
    category: 'noodle_soup',
    per100g: n(68, 4.4, 9.6, 1.3, 0.4),
    dataQuality: 'medium',
    sourceReference: RECIPE('180 g cooked rice noodles, 70 g poached chicken, 300 ml chicken broth and herbs'),
    portions: P.noodleSoup(),
  },
  {
    externalId: 'vn-pho-tai',
    nameVi: 'Phở tái',
    nameEn: 'Rare beef noodle soup',
    category: 'noodle_soup',
    per100g: n(72, 4.8, 9.2, 1.7, 0.4),
    dataQuality: 'medium',
    sourceReference: RECIPE('as phở bò, with rare-cooked eye of round rather than brisket'),
    portions: P.noodleSoup(),
  },
  {
    externalId: 'vn-bun-bo-hue',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Bún bò Huế',
    nameEn: 'Hue-style spicy beef noodle soup',
    category: 'noodle_soup',
    per100g: n(88, 5.2, 9.8, 3.2, 0.5),
    dataQuality: 'medium',
    sourceReference: RECIPE('thick rice noodles, beef shank and pork knuckle in a lemongrass and chilli oil broth'),
    portions: P.noodleSoup(),
  },
  {
    externalId: 'vn-bun-rieu-cua',
    nameVi: 'Bún riêu cua',
    nameEn: 'Crab paste noodle soup',
    category: 'noodle_soup',
    per100g: n(72, 4.4, 9.0, 2.2, 0.6),
    dataQuality: 'medium',
    sourceReference: RECIPE('rice vermicelli, freshwater crab paste, tomato and tofu puffs in a tamarind broth'),
    portions: P.noodleSoup(),
  },
  {
    externalId: 'vn-bun-moc',
    nameVi: 'Bún mọc',
    nameEn: 'Pork meatball noodle soup',
    category: 'noodle_soup',
    per100g: n(78, 4.6, 9.6, 2.4, 0.4),
    dataQuality: 'medium',
    sourceReference: RECIPE('rice vermicelli, pork meatballs and wood ear in pork bone broth'),
    portions: P.noodleSoup(),
  },
  {
    externalId: 'vn-hu-tieu',
    nameVi: 'Hủ tiếu',
    nameEn: 'Southern pork and seafood noodle soup',
    category: 'noodle_soup',
    per100g: n(80, 4.8, 10.6, 2.2, 0.4),
    dataQuality: 'medium',
    sourceReference: RECIPE('tapioca-rice noodles, pork loin, prawn and quail egg in a lightly sweetened pork broth'),
    portions: P.noodleSoup(),
  },
  {
    externalId: 'vn-hu-tieu-kho',
    nameVi: 'Hủ tiếu khô',
    nameEn: 'Dry hu tieu, broth on the side',
    category: 'noodle_dry',
    per100g: n(148, 7.4, 21.0, 3.8, 0.7),
    dataQuality: 'medium',
    sourceReference: RECIPE('as hủ tiếu, noodles dressed with soy and fried shallot, broth served separately'),
    portions: P.noodleDry(),
  },
  {
    externalId: 'vn-mi-quang',
    nameVi: 'Mì Quảng',
    nameEn: 'Quang-style turmeric noodles',
    category: 'noodle_soup',
    per100g: n(118, 6.4, 14.0, 4.0, 0.8),
    dataQuality: 'medium',
    sourceReference: RECIPE('turmeric rice noodles with pork, prawn and peanut in a small amount of rich broth'),
    portions: [
      { label: '1 bowl', labelVi: '1 tô', grams: 400, isDefault: true },
      { label: 'large bowl', labelVi: 'tô lớn', grams: 500 },
    ],
  },
  {
    externalId: 'vn-banh-canh-cua',
    nameVi: 'Bánh canh cua',
    nameEn: 'Thick tapioca noodle soup with crab',
    category: 'noodle_soup',
    per100g: n(86, 4.6, 13.2, 1.8, 0.3),
    dataQuality: 'medium',
    sourceReference: RECIPE('tapioca noodles, crab meat and quail egg in a thickened broth'),
    portions: P.noodleSoup(),
  },
  {
    externalId: 'vn-mien-ga',
    nameVi: 'Miến gà',
    nameEn: 'Glass noodle chicken soup',
    category: 'noodle_soup',
    per100g: n(62, 3.8, 9.4, 1.0, 0.3),
    dataQuality: 'medium',
    sourceReference: RECIPE('glass noodles and shredded chicken in chicken broth'),
    portions: P.noodleSoup(),
  },
  {
    externalId: 'vn-bun-cha-ca',
    nameVi: 'Bún chả cá',
    nameEn: 'Fish cake noodle soup',
    category: 'noodle_soup',
    per100g: n(74, 5.0, 9.2, 1.9, 0.4),
    dataQuality: 'medium',
    sourceReference: RECIPE('rice vermicelli and fried fish cake in a light fish broth'),
    portions: P.noodleSoup(),
  },
  {
    externalId: 'vn-bun-thit-nuong',
    nameVi: 'Bún thịt nướng',
    nameEn: 'Vermicelli with grilled pork',
    category: 'noodle_dry',
    per100g: n(152, 7.8, 20.4, 4.4, 1.1),
    dataQuality: 'medium',
    sourceReference: RECIPE('180 g rice vermicelli, 80 g grilled pork, herbs, pickles, peanut and nước chấm'),
    portions: [
      { label: '1 bowl', labelVi: '1 tô', grams: 350, isDefault: true },
      { label: 'large bowl', labelVi: 'tô lớn', grams: 450 },
    ],
  },
  {
    externalId: 'vn-bun-cha',
    nameVi: 'Bún chả',
    nameEn: 'Grilled pork patties with vermicelli',
    category: 'noodle_dry',
    per100g: n(158, 8.6, 17.8, 5.8, 0.9),
    dataQuality: 'medium',
    sourceReference: RECIPE('grilled pork belly and patties in diluted fish sauce, with vermicelli and herbs'),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 400, isDefault: true }],
  },
  {
    externalId: 'vn-bun-dau-mam-tom',
    nameVi: 'Bún đậu mắm tôm',
    nameEn: 'Vermicelli with fried tofu and shrimp paste',
    category: 'noodle_dry',
    per100g: n(176, 8.2, 18.6, 7.8, 1.4),
    dataQuality: 'medium',
    sourceReference: RECIPE('vermicelli sheets, deep-fried tofu, boiled pork and herbs with fermented shrimp paste'),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 350, isDefault: true }],
  },
  {
    externalId: 'vn-bun-mam',
    nameVi: 'Bún mắm',
    nameEn: 'Fermented fish noodle soup',
    category: 'noodle_soup',
    per100g: n(84, 5.4, 9.6, 2.6, 0.6),
    dataQuality: 'low',
    sourceReference: RECIPE(
      'rice vermicelli with fermented fish broth, pork belly, prawn and aubergine; recipe varies widely by region, so this is an order-of-magnitude estimate',
    ),
    portions: P.noodleSoup(),
  },
  {
    externalId: 'vn-cao-lau',
    nameVi: 'Cao lầu',
    nameEn: 'Hoi An cao lau noodles',
    category: 'noodle_dry',
    per100g: n(146, 7.2, 20.6, 3.8, 0.8),
    dataQuality: 'low',
    sourceReference: RECIPE(
      'thick Hoi An noodles with char siu pork, greens and crisp croutons; a regional speciality with little published composition data',
    ),
    portions: P.noodleDry(),
  },
  {
    externalId: 'vn-mi-xao-bo',
    nameVi: 'Mì xào bò',
    nameEn: 'Stir-fried noodles with beef',
    category: 'noodle_dry',
    per100g: n(168, 8.0, 20.2, 6.0, 1.2),
    dataQuality: 'medium',
    sourceReference: RECIPE('egg noodles stir-fried with beef, onion and greens in 8 g oil per serving'),
    portions: P.noodleDry(),
  },
  {
    externalId: 'vn-banh-xeo',
    nameVi: 'Bánh xèo',
    nameEn: 'Crispy savoury rice pancake',
    category: 'street_food',
    per100g: n(224, 7.4, 22.0, 11.6, 1.3),
    dataQuality: 'medium',
    sourceReference: RECIPE('rice batter with turmeric and coconut milk, pork, prawn and bean sprouts, pan-fried in oil'),
    portions: P.piece(150, '1 cái'),
  },
  {
    externalId: 'vn-banh-khot',
    nameVi: 'Bánh khọt',
    nameEn: 'Mini savoury rice pancakes',
    category: 'street_food',
    per100g: n(238, 7.0, 22.4, 13.2, 1.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('rice batter cups with prawn, fried in coconut oil'),
    portions: [{ label: '1 serving', labelVi: '1 phần (8 cái)', grams: 160, isDefault: true }],
  },
  {
    externalId: 'vn-goi-cuon',
    nameVi: 'Gỏi cuốn',
    nameEn: 'Fresh summer rolls',
    category: 'street_food',
    per100g: n(112, 6.2, 17.4, 1.4, 1.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('rice paper with vermicelli, boiled pork, prawn and herbs; dipping sauce excluded'),
    portions: P.piece(60, '1 cuốn'),
  },
  {
    externalId: 'vn-cha-gio',
    nameVi: 'Chả giò',
    nameEn: 'Fried spring rolls',
    category: 'street_food',
    per100g: n(286, 10.4, 26.0, 15.6, 1.2),
    dataQuality: 'medium',
    sourceReference: RECIPE('minced pork, wood ear, glass noodle and taro in rice paper, deep fried'),
    portions: P.piece(40, '1 cuốn'),
  },
  {
    externalId: 'vn-banh-bao',
    nameVi: 'Bánh bao',
    nameEn: 'Steamed pork bun',
    category: 'breakfast',
    per100g: n(226, 8.8, 32.0, 6.6, 1.2),
    dataQuality: 'medium',
    sourceReference: RECIPE('wheat dough bun filled with minced pork, quail egg and Chinese sausage'),
    portions: P.piece(120, '1 cái'),
  },
  {
    externalId: 'vn-banh-beo',
    nameVi: 'Bánh bèo',
    nameEn: 'Steamed rice cakes with dried shrimp',
    category: 'street_food',
    per100g: n(132, 3.8, 22.6, 3.0, 0.5),
    dataQuality: 'medium',
    sourceReference: RECIPE('steamed rice flour discs topped with dried shrimp floss, crackling and scallion oil'),
    portions: [{ label: '1 serving', labelVi: '1 phần (10 chén)', grams: 200, isDefault: true }],
  },
  {
    externalId: 'vn-banh-bot-loc',
    nameVi: 'Bánh bột lọc',
    nameEn: 'Tapioca dumplings with prawn and pork',
    category: 'street_food',
    per100g: n(168, 5.4, 30.0, 3.2, 0.4),
    dataQuality: 'medium',
    sourceReference: RECIPE('tapioca dough dumplings filled with prawn and pork belly, steamed'),
    portions: P.piece(25, '1 cái'),
  },
];
