import { P, RECIPE, USDA, n, type SeedFood } from './shared.js';

/**
 * Rau, canh and fruit.
 *
 * Raw and boiled vegetables are `high` — a cucumber is a cucumber. Stir-fries are
 * `medium` because the oil is the variable, and canh is `medium` because how much of the
 * bowl is broth changes everything per 100 g.
 */
export const PRODUCE: SeedFood[] = [
  // ── Rau ───────────────────────────────────────────────────────────────────
  {
    externalId: 'vn-rau-muong-xao-toi',
    nameVi: 'Rau muống xào tỏi',
    nameEn: 'Water spinach stir-fried with garlic',
    category: 'vegetable',
    per100g: n(84, 2.9, 4.2, 6.4, 2.1),
    dataQuality: 'medium',
    sourceReference: RECIPE('water spinach stir-fried with garlic in 6 g oil per 100 g finished dish'),
    portions: P.vegetable(),
  },
  {
    externalId: 'vn-rau-muong-luoc',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Rau muống luộc',
    nameEn: 'Boiled water spinach',
    category: 'vegetable',
    per100g: n(24, 2.6, 3.1, 0.2, 2.1),
    dataQuality: 'high',
    sourceReference: USDA('water spinach, boiled, drained'),
    portions: P.vegetable(),
  },
  {
    externalId: 'vn-rau-cai-luoc',
    nameVi: 'Rau cải luộc',
    nameEn: 'Boiled mustard greens',
    category: 'vegetable',
    per100g: n(22, 2.2, 3.4, 0.3, 2.0),
    dataQuality: 'high',
    sourceReference: USDA('mustard greens, boiled, drained'),
    portions: P.vegetable(),
  },
  {
    externalId: 'vn-gia-xao',
    nameVi: 'Giá xào',
    nameEn: 'Stir-fried bean sprouts',
    category: 'vegetable',
    per100g: n(72, 3.1, 6.0, 4.4, 1.8),
    dataQuality: 'medium',
    sourceReference: RECIPE('mung bean sprouts stir-fried with garlic chives in 4 g oil per 100 g'),
    portions: P.vegetable(),
  },
  {
    externalId: 'vn-bap-cai-luoc',
    nameVi: 'Bắp cải luộc',
    nameEn: 'Boiled cabbage',
    category: 'vegetable',
    per100g: n(23, 1.3, 5.5, 0.1, 2.3),
    dataQuality: 'high',
    sourceReference: USDA('cabbage, boiled, drained'),
    portions: P.vegetable(),
  },
  {
    externalId: 'vn-su-su-xao',
    nameVi: 'Su su xào',
    nameEn: 'Stir-fried chayote',
    category: 'vegetable',
    per100g: n(66, 1.1, 5.4, 4.6, 1.7),
    dataQuality: 'medium',
    sourceReference: RECIPE('chayote stir-fried with garlic in 4 g oil per 100 g'),
    portions: P.vegetable(),
  },
  {
    externalId: 'vn-ca-rot-luoc',
    nameVi: 'Cà rốt luộc',
    nameEn: 'Boiled carrot',
    category: 'vegetable',
    per100g: n(35, 0.8, 8.2, 0.2, 3.0),
    dataQuality: 'high',
    sourceReference: USDA('carrots, boiled, drained'),
    portions: P.vegetable(),
  },
  {
    externalId: 'vn-dua-leo',
    nameVi: 'Dưa leo',
    nameEn: 'Cucumber, raw',
    category: 'vegetable',
    per100g: n(15, 0.7, 3.6, 0.1, 0.5),
    dataQuality: 'high',
    sourceReference: USDA('cucumber, with peel, raw'),
    portions: P.vegetable(),
  },
  {
    externalId: 'vn-ca-chua',
    nameVi: 'Cà chua',
    nameEn: 'Tomato, raw',
    category: 'vegetable',
    per100g: n(18, 0.9, 3.9, 0.2, 1.2),
    dataQuality: 'high',
    sourceReference: USDA('tomatoes, red, ripe, raw'),
    portions: P.vegetable(),
  },
  {
    externalId: 'vn-nam-rom-xao',
    nameVi: 'Nấm rơm xào',
    nameEn: 'Stir-fried straw mushrooms',
    category: 'vegetable',
    per100g: n(78, 3.2, 5.0, 5.2, 2.2),
    dataQuality: 'medium',
    sourceReference: RECIPE('straw mushrooms stir-fried with garlic in 4 g oil per 100 g'),
    portions: P.vegetable(),
  },
  {
    externalId: 'vn-goi-du-du',
    nameVi: 'Gỏi đu đủ',
    nameEn: 'Green papaya salad',
    category: 'vegetable',
    per100g: n(78, 3.6, 12.4, 1.8, 1.9),
    dataQuality: 'medium',
    sourceReference: RECIPE('shredded green papaya with dried beef, peanut, herbs and sweet fish sauce dressing'),
    portions: [{ label: '1 plate', labelVi: '1 đĩa', grams: 150, isDefault: true }],
  },
  {
    externalId: 'vn-dua-chua',
    nameVi: 'Dưa chua',
    nameEn: 'Pickled mustard greens',
    category: 'condiment',
    per100g: n(21, 1.4, 3.2, 0.2, 1.8),
    dataQuality: 'medium',
    sourceReference: RECIPE('mustard greens fermented in brine; sodium high, energy negligible'),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 50, isDefault: true }],
  },

  // ── Canh ──────────────────────────────────────────────────────────────────
  {
    externalId: 'vn-canh-chua-ca',
    nameVi: 'Canh chua cá',
    nameEn: 'Sour tamarind fish soup',
    category: 'soup',
    per100g: n(44, 3.8, 4.2, 1.2, 0.6),
    dataQuality: 'medium',
    sourceReference: RECIPE('tamarind broth with fish, pineapple, okra, bean sprouts and elephant ear stem'),
    portions: P.soup(),
  },
  {
    externalId: 'vn-canh-rau-ngot',
    nameVi: 'Canh rau ngót',
    nameEn: 'Katuk leaf soup with minced pork',
    category: 'soup',
    per100g: n(28, 2.8, 2.2, 0.9, 1.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('katuk leaves simmered with minced pork in a light broth'),
    portions: P.soup(),
  },
  {
    externalId: 'vn-canh-bi-dao',
    nameVi: 'Canh bí đao',
    nameEn: 'Winter melon soup',
    category: 'soup',
    per100g: n(22, 1.6, 2.6, 0.6, 0.6),
    dataQuality: 'medium',
    sourceReference: RECIPE('winter melon simmered with minced pork or prawn in a light broth'),
    portions: P.soup(),
  },
  {
    externalId: 'vn-canh-cai-thit-bam',
    nameVi: 'Canh cải thịt bằm',
    nameEn: 'Mustard green soup with minced pork',
    category: 'soup',
    per100g: n(30, 2.9, 2.0, 1.2, 0.9),
    dataQuality: 'medium',
    sourceReference: RECIPE('mustard greens simmered with minced pork'),
    portions: P.soup(),
  },
  {
    externalId: 'vn-canh-rau',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Canh rau',
    nameEn: 'Mixed vegetable soup',
    category: 'soup',
    per100g: n(22, 1.2, 3.0, 0.5, 0.9),
    dataQuality: 'low',
    sourceReference: RECIPE(
      'generic mixed-vegetable clear soup; "canh rau" names a whole family of dishes, so this is a deliberately conservative stand-in that the user should refine',
    ),
    portions: P.soup(),
  },
  {
    externalId: 'vn-canh-kho-qua',
    nameVi: 'Canh khổ qua nhồi thịt',
    nameEn: 'Stuffed bitter melon soup',
    category: 'soup',
    per100g: n(46, 3.6, 3.4, 2.1, 1.3),
    dataQuality: 'medium',
    sourceReference: RECIPE('bitter melon stuffed with minced pork and wood ear, simmered'),
    portions: P.soup(),
  },
  {
    externalId: 'vn-lau-thai',
    nameVi: 'Lẩu Thái',
    nameEn: 'Thai-style hotpot broth with seafood',
    category: 'soup',
    per100g: n(52, 4.4, 3.6, 2.2, 0.5),
    dataQuality: 'low',
    sourceReference: RECIPE(
      'spicy sour hotpot with mixed seafood and vegetables; what ends up eaten varies enormously, so treat as indicative',
    ),
    portions: [{ label: '1 bowl', labelVi: '1 tô', grams: 400, isDefault: true }],
  },

  // ── Trái cây ──────────────────────────────────────────────────────────────
  {
    externalId: 'vn-chuoi',
    nameVi: 'Chuối',
    nameEn: 'Banana',
    category: 'fruit',
    per100g: n(89, 1.1, 22.8, 0.3, 2.6),
    dataQuality: 'high',
    sourceReference: USDA('bananas, raw'),
    portions: P.wholeFruit(100),
  },
  {
    externalId: 'vn-tao',
    nameVi: 'Táo',
    nameEn: 'Apple',
    category: 'fruit',
    per100g: n(52, 0.3, 13.8, 0.2, 2.4),
    dataQuality: 'high',
    sourceReference: USDA('apples, raw, with skin'),
    portions: P.wholeFruit(180),
  },
  {
    externalId: 'vn-cam',
    nameVi: 'Cam',
    nameEn: 'Orange',
    category: 'fruit',
    per100g: n(47, 0.9, 11.8, 0.1, 2.4),
    dataQuality: 'high',
    sourceReference: USDA('oranges, raw'),
    portions: P.wholeFruit(150),
  },
  {
    externalId: 'vn-xoai',
    nameVi: 'Xoài',
    nameEn: 'Mango',
    category: 'fruit',
    per100g: n(60, 0.8, 15.0, 0.4, 1.6),
    dataQuality: 'high',
    sourceReference: USDA('mangos, raw'),
    portions: P.wholeFruit(200),
  },
  {
    externalId: 'vn-du-du',
    nameVi: 'Đu đủ',
    nameEn: 'Papaya',
    category: 'fruit',
    per100g: n(43, 0.5, 10.8, 0.3, 1.7),
    dataQuality: 'high',
    sourceReference: USDA('papayas, raw'),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 150, isDefault: true }],
  },
  {
    externalId: 'vn-dua-hau',
    nameVi: 'Dưa hấu',
    nameEn: 'Watermelon',
    category: 'fruit',
    per100g: n(30, 0.6, 7.6, 0.2, 0.4),
    dataQuality: 'high',
    sourceReference: USDA('watermelon, raw'),
    portions: [{ label: '1 slice', labelVi: '1 miếng', grams: 200, isDefault: true }],
  },
  {
    externalId: 'vn-thanh-long',
    nameVi: 'Thanh long',
    nameEn: 'Dragon fruit',
    category: 'fruit',
    per100g: n(60, 1.2, 13.0, 0.4, 3.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('white-fleshed pitaya; published values vary by cultivar'),
    portions: P.wholeFruit(300),
  },
  {
    externalId: 'vn-nhan',
    nameVi: 'Nhãn',
    nameEn: 'Longan',
    category: 'fruit',
    per100g: n(60, 1.3, 15.1, 0.1, 1.1),
    dataQuality: 'high',
    sourceReference: USDA('longans, raw'),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 100, isDefault: true }],
  },
  {
    externalId: 'vn-vai',
    nameVi: 'Vải',
    nameEn: 'Lychee',
    category: 'fruit',
    per100g: n(66, 0.8, 16.5, 0.4, 1.3),
    dataQuality: 'high',
    sourceReference: USDA('litchis, raw'),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 100, isDefault: true }],
  },
  {
    externalId: 'vn-oi',
    nameVi: 'Ổi',
    nameEn: 'Guava',
    category: 'fruit',
    per100g: n(68, 2.6, 14.3, 1.0, 5.4),
    dataQuality: 'high',
    sourceReference: USDA('guavas, common, raw'),
    portions: P.wholeFruit(150),
  },
  {
    externalId: 'vn-buoi',
    nameVi: 'Bưởi',
    nameEn: 'Pomelo',
    category: 'fruit',
    per100g: n(38, 0.8, 9.6, 0.0, 1.0),
    dataQuality: 'high',
    sourceReference: USDA('pummelo, raw'),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 150, isDefault: true }],
  },
  {
    externalId: 'vn-dua-luoi',
    nameVi: 'Dưa lưới',
    nameEn: 'Cantaloupe melon',
    category: 'fruit',
    per100g: n(34, 0.8, 8.2, 0.2, 0.9),
    dataQuality: 'high',
    sourceReference: USDA('melons, cantaloupe, raw'),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 150, isDefault: true }],
  },
  {
    externalId: 'vn-bo',
    nameVi: 'Bơ',
    nameEn: 'Avocado',
    category: 'fruit',
    per100g: n(160, 2.0, 8.5, 14.7, 6.7),
    dataQuality: 'high',
    sourceReference: USDA('avocados, raw'),
    portions: P.wholeFruit(200),
  },
];
