import { P, RECIPE, USDA, n, type SeedFood } from './shared.js';

/**
 * Món mặn — the savoury dishes at the centre of a Vietnamese meal — plus the plain meats,
 * seafood, eggs and tofu people log as components.
 *
 * The plain cuts are `high`: a boiled chicken breast is a boiled chicken breast. The
 * braised and caramelised dishes are `medium`, because the amount of caramel, fat and
 * fish sauce is exactly what varies between households.
 */
export const PROTEINS: SeedFood[] = [
  // ── Món mặn ───────────────────────────────────────────────────────────────
  {
    externalId: 'vn-thit-kho-trung',
    nameVi: 'Thịt kho trứng',
    nameEn: 'Caramelised braised pork belly with egg',
    category: 'meat',
    per100g: n(232, 14.2, 5.4, 17.0, 0.1),
    dataQuality: 'medium',
    sourceReference: RECIPE(
      'pork belly braised with coconut water, fish sauce, caramel and hard-boiled egg; fat content varies most with the cut',
    ),
    portions: P.mainDish(120),
  },
  {
    externalId: 'vn-thit-kho-to',
    nameVi: 'Thịt kho tộ',
    nameEn: 'Clay pot caramelised pork',
    category: 'meat',
    per100g: n(248, 15.0, 5.0, 18.6, 0.1),
    dataQuality: 'medium',
    sourceReference: RECIPE('pork belly braised in a clay pot with caramel and fish sauce, reduced further than thịt kho trứng'),
    portions: P.mainDish(120),
  },
  {
    externalId: 'vn-ca-kho-to',
    nameVi: 'Cá kho tộ',
    nameEn: 'Clay pot caramelised fish',
    category: 'seafood',
    per100g: n(158, 18.6, 4.2, 7.4, 0.1),
    dataQuality: 'medium',
    sourceReference: RECIPE('basa or catfish steaks braised with caramel, fish sauce and pepper'),
    portions: [
      { label: '1 piece', labelVi: '1 khứa', grams: 80, isDefault: true },
      { label: '1 serving', labelVi: '1 phần', grams: 120 },
    ],
  },
  {
    externalId: 'vn-ga-kho-gung',
    nameVi: 'Gà kho gừng',
    nameEn: 'Braised chicken with ginger',
    category: 'meat',
    per100g: n(184, 20.4, 4.6, 9.2, 0.3),
    dataQuality: 'medium',
    sourceReference: RECIPE('bone-in chicken braised with ginger, fish sauce and a little caramel'),
    portions: P.mainDish(120),
  },
  {
    externalId: 'vn-suon-ram-man',
    nameVi: 'Sườn ram mặn',
    nameEn: 'Caramelised pork ribs',
    category: 'meat',
    per100g: n(268, 17.2, 6.8, 19.0, 0.2),
    dataQuality: 'medium',
    sourceReference: RECIPE('pork spare ribs seared then reduced in caramel and fish sauce'),
    portions: P.mainDish(120),
  },
  {
    externalId: 'vn-thit-nuong',
    nameVi: 'Thịt nướng',
    nameEn: 'Grilled marinated pork',
    category: 'meat',
    per100g: n(238, 21.0, 6.2, 14.2, 0.2),
    dataQuality: 'medium',
    sourceReference: RECIPE('pork shoulder marinated in lemongrass, sugar and fish sauce, charcoal grilled'),
    portions: P.mainDish(100),
  },
  {
    externalId: 'vn-ga-nuong',
    nameVi: 'Gà nướng',
    nameEn: 'Grilled chicken',
    category: 'meat',
    per100g: n(197, 27.0, 2.0, 8.8, 0.1),
    dataQuality: 'medium',
    sourceReference: RECIPE('bone-in chicken marinated with honey and fish sauce, grilled'),
    portions: P.mainDish(120),
  },
  {
    externalId: 'vn-bo-luc-lac',
    nameVi: 'Bò lúc lắc',
    nameEn: 'Shaking beef',
    category: 'meat',
    per100g: n(212, 22.4, 5.0, 11.4, 0.5),
    dataQuality: 'medium',
    sourceReference: RECIPE('cubed beef sirloin seared with butter, onion and pepper'),
    portions: P.mainDish(120),
  },
  {
    externalId: 'vn-tom-rim',
    nameVi: 'Tôm rim',
    nameEn: 'Caramelised prawns',
    category: 'seafood',
    per100g: n(142, 19.8, 6.4, 4.0, 0.1),
    dataQuality: 'medium',
    sourceReference: RECIPE('prawns reduced in fish sauce, sugar and pepper'),
    portions: P.mainDish(100),
  },
  {
    externalId: 'vn-trung-chien',
    nameVi: 'Trứng chiên',
    nameEn: 'Vietnamese fried egg omelette',
    category: 'egg',
    per100g: n(196, 13.0, 1.6, 15.2, 0.1),
    dataQuality: 'medium',
    sourceReference: RECIPE('two hen eggs with scallion, fried in 5 g oil'),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 110, isDefault: true }],
  },
  {
    externalId: 'vn-trung-op-la',
    nameVi: 'Trứng ốp la',
    nameEn: 'Fried egg, sunny side up',
    category: 'egg',
    per100g: n(196, 13.6, 0.8, 15.3, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('egg, whole, fried'),
    portions: P.piece(55, '1 quả'),
  },
  {
    externalId: 'vn-trung-luoc',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Trứng luộc',
    nameEn: 'Boiled egg',
    category: 'egg',
    per100g: n(155, 12.6, 1.1, 10.6, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('egg, whole, hard-boiled'),
    portions: P.piece(50, '1 quả'),
  },
  {
    externalId: 'vn-trung-vit-lon',
    nameVi: 'Trứng vịt lộn',
    nameEn: 'Balut',
    category: 'egg',
    per100g: n(181, 13.6, 1.4, 13.0, 0.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('fertilised duck egg, boiled; composition close to whole duck egg'),
    portions: P.piece(70, '1 quả'),
  },
  {
    externalId: 'vn-cha-lua',
    nameVi: 'Chả lụa',
    nameEn: 'Vietnamese pork sausage',
    category: 'meat',
    per100g: n(196, 15.4, 3.0, 13.6, 0.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('lean pork paste with fish sauce and starch, steamed in banana leaf'),
    portions: [{ label: '1 slice', labelVi: '1 lát', grams: 30, isDefault: true }],
  },
  {
    externalId: 'vn-cha-ca',
    nameVi: 'Chả cá',
    nameEn: 'Fried fish cake',
    category: 'seafood',
    per100g: n(186, 14.8, 9.4, 10.2, 0.3),
    dataQuality: 'medium',
    sourceReference: RECIPE('white fish paste with dill and starch, shallow fried'),
    portions: [{ label: '1 piece', labelVi: '1 miếng', grams: 40, isDefault: true }],
  },
  {
    externalId: 'vn-nem-nuong',
    nameVi: 'Nem nướng',
    nameEn: 'Grilled pork sausage skewer',
    category: 'street_food',
    per100g: n(246, 17.8, 8.2, 15.8, 0.2),
    dataQuality: 'medium',
    sourceReference: RECIPE('minced pork with garlic and sugar, grilled on skewers'),
    portions: P.piece(40, '1 xiên'),
  },

  // ── Plain meats and seafood ───────────────────────────────────────────────
  {
    externalId: 'vn-uc-ga-luoc',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Ức gà luộc',
    nameEn: 'Boiled chicken breast, skinless',
    category: 'meat',
    per100g: n(165, 31.0, 0.0, 3.6, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('chicken breast, skinless, cooked'),
    portions: P.mainDish(120),
  },
  {
    externalId: 'vn-dui-ga',
    nameVi: 'Đùi gà',
    nameEn: 'Chicken thigh, cooked',
    category: 'meat',
    per100g: n(209, 26.0, 0.0, 10.9, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('chicken thigh, skinless, cooked'),
    portions: P.mainDish(120),
  },
  {
    externalId: 'vn-thit-heo-nac',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Thịt heo nạc',
    nameEn: 'Lean pork, cooked',
    category: 'meat',
    per100g: n(242, 27.3, 0.0, 14.0, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('pork loin, cooked'),
    portions: P.mainDish(100),
  },
  {
    externalId: 'vn-thit-ba-chi',
    nameVi: 'Thịt ba chỉ',
    nameEn: 'Pork belly, cooked',
    category: 'meat',
    per100g: n(518, 9.3, 0.0, 53.0, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('pork belly, cooked'),
    portions: P.mainDish(80),
  },
  {
    externalId: 'vn-thit-bo',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Thịt bò',
    nameEn: 'Lean beef, cooked',
    category: 'meat',
    per100g: n(250, 26.0, 0.0, 15.0, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('beef, lean cut, cooked'),
    portions: P.mainDish(100),
  },
  {
    externalId: 'vn-ca-basa',
    nameVi: 'Cá basa',
    nameEn: 'Basa fish, cooked',
    category: 'seafood',
    per100g: n(124, 18.0, 0.0, 5.6, 0.0),
    dataQuality: 'medium',
    sourceReference: RECIPE('farmed pangasius fillet, cooked; fat varies with farming practice'),
    portions: P.mainDish(120),
  },
  {
    externalId: 'vn-ca-thu',
    nameVi: 'Cá thu',
    nameEn: 'Mackerel, cooked',
    category: 'seafood',
    per100g: n(205, 23.8, 0.0, 11.6, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('mackerel, cooked'),
    portions: P.mainDish(100),
  },
  {
    externalId: 'vn-ca-hoi',
    nameVi: 'Cá hồi',
    nameEn: 'Salmon, cooked',
    category: 'seafood',
    per100g: n(206, 22.1, 0.0, 12.4, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('salmon, cooked'),
    portions: P.mainDish(120),
  },
  {
    externalId: 'vn-tom',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Tôm',
    nameEn: 'Prawns, cooked',
    category: 'seafood',
    per100g: n(99, 20.9, 0.2, 1.1, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('shrimp, cooked'),
    portions: P.mainDish(100),
  },
  {
    externalId: 'vn-muc',
    nameVi: 'Mực',
    nameEn: 'Squid, cooked',
    category: 'seafood',
    per100g: n(175, 17.9, 7.8, 7.5, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('squid, cooked'),
    portions: P.mainDish(100),
  },
  {
    externalId: 'vn-nghieu',
    nameVi: 'Nghêu',
    nameEn: 'Clams, cooked',
    category: 'seafood',
    per100g: n(148, 25.5, 5.1, 1.9, 0.0),
    dataQuality: 'high',
    sourceReference: USDA('clams, cooked'),
    portions: P.mainDish(100),
  },

  // ── Đậu hũ & thực vật giàu đạm ────────────────────────────────────────────
  {
    externalId: 'vn-dau-hu-trang',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Đậu hũ trắng',
    nameEn: 'Firm tofu',
    category: 'tofu_bean',
    per100g: n(144, 15.8, 4.3, 8.7, 2.3),
    dataQuality: 'high',
    sourceReference: USDA('tofu, firm, raw'),
    portions: [{ label: '1 piece', labelVi: '1 miếng', grams: 80, isDefault: true }],
  },
  {
    externalId: 'vn-dau-hu-chien',
    nameVi: 'Đậu hũ chiên',
    nameEn: 'Fried tofu',
    category: 'tofu_bean',
    per100g: n(271, 17.2, 10.5, 20.2, 3.9),
    dataQuality: 'high',
    sourceReference: USDA('tofu, fried'),
    portions: [{ label: '1 piece', labelVi: '1 miếng', grams: 40, isDefault: true }],
  },
  {
    externalId: 'vn-dau-hu-sot-ca',
    nameVi: 'Đậu hũ sốt cà',
    nameEn: 'Tofu in tomato sauce',
    category: 'tofu_bean',
    per100g: n(138, 9.4, 7.2, 8.2, 1.6),
    dataQuality: 'medium',
    sourceReference: RECIPE('fried tofu simmered in tomato, garlic and a little sugar'),
    portions: P.mainDish(150),
  },
  {
    externalId: 'vn-dau-phong-rang',
    nameVi: 'Đậu phộng rang',
    nameEn: 'Roasted peanuts',
    category: 'snack',
    per100g: n(587, 24.4, 21.5, 49.7, 8.0),
    dataQuality: 'high',
    sourceReference: USDA('peanuts, dry roasted'),
    portions: [{ label: '1 tablespoon', labelVi: '1 muỗng canh', grams: 15, isDefault: true }],
  },
];
