import { P, RECIPE, USDA, n, type SeedFood } from './shared.js';

/** Cơm, xôi, cháo, bánh mì and the plain noodles. */
export const STAPLES: SeedFood[] = [
  // ── Cơm & tinh bột ────────────────────────────────────────────────────────
  {
    externalId: 'vn-com-trang',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Cơm trắng',
    nameEn: 'Steamed white rice',
    category: 'rice_grain',
    per100g: n(130, 2.7, 28.2, 0.3, 0.4),
    dataQuality: 'high',
    sourceReference: USDA('cooked white long-grain rice'),
    portions: P.rice(),
  },
  {
    externalId: 'vn-com-gao-lut',
    nameVi: 'Cơm gạo lứt',
    nameEn: 'Steamed brown rice',
    category: 'rice_grain',
    per100g: n(123, 2.7, 25.6, 1.0, 1.6),
    dataQuality: 'high',
    sourceReference: USDA('cooked brown long-grain rice'),
    portions: P.rice(),
  },
  {
    externalId: 'vn-com-tam',
    nameVi: 'Cơm tấm',
    nameEn: 'Broken rice (plain)',
    category: 'rice_grain',
    per100g: n(134, 2.8, 29.0, 0.3, 0.4),
    dataQuality: 'medium',
    sourceReference: RECIPE('broken rice grains, cooked; close to white rice with slightly lower water uptake'),
    portions: P.rice(),
  },
  {
    externalId: 'vn-com-tam-suon-bi-cha',
    nameVi: 'Cơm tấm sườn bì chả',
    nameEn: 'Broken rice with grilled pork chop, shredded pork skin and egg meatloaf',
    category: 'rice_grain',
    per100g: n(178, 8.4, 22.0, 6.2, 0.6),
    dataQuality: 'medium',
    sourceReference: RECIPE('200 g broken rice, 90 g grilled pork chop, 25 g bì, 40 g chả trứng, scallion oil'),
    portions: [
      { label: '1 plate', labelVi: '1 đĩa', grams: 400, isDefault: true },
      { label: 'large plate', labelVi: 'đĩa đặc biệt', grams: 520 },
    ],
  },
  {
    externalId: 'vn-com-chien-duong-chau',
    nameVi: 'Cơm chiên Dương Châu',
    nameEn: 'Yangzhou fried rice',
    category: 'rice_grain',
    per100g: n(186, 6.1, 25.4, 6.5, 0.8),
    dataQuality: 'medium',
    sourceReference: RECIPE('cooked rice fried with egg, Chinese sausage, peas, carrot and 8 g oil per serving'),
    portions: [{ label: '1 plate', labelVi: '1 đĩa', grams: 300, isDefault: true }],
  },
  {
    externalId: 'vn-xoi-trang',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Xôi trắng',
    nameEn: 'Steamed sticky rice',
    category: 'rice_grain',
    per100g: n(190, 3.5, 41.0, 0.4, 0.6),
    dataQuality: 'high',
    sourceReference: USDA('cooked glutinous rice'),
    portions: [
      { label: '1 serving', labelVi: '1 phần', grams: 150, isDefault: true },
      { label: 'small pack', labelVi: 'gói nhỏ', grams: 100 },
    ],
  },
  {
    externalId: 'vn-xoi-man',
    nameVi: 'Xôi mặn',
    nameEn: 'Savoury sticky rice with pork floss and sausage',
    category: 'breakfast',
    per100g: n(232, 7.8, 38.0, 5.4, 0.7),
    dataQuality: 'medium',
    sourceReference: RECIPE('150 g sticky rice, 15 g pork floss, 20 g Chinese sausage, scallion oil'),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 200, isDefault: true }],
  },
  {
    externalId: 'vn-xoi-gac',
    nameVi: 'Xôi gấc',
    nameEn: 'Gac fruit sticky rice',
    category: 'rice_grain',
    per100g: n(205, 3.6, 42.5, 2.4, 0.9),
    dataQuality: 'medium',
    sourceReference: RECIPE('glutinous rice with gac pulp, coconut and a little sugar'),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 150, isDefault: true }],
  },
  {
    externalId: 'vn-chao-trang',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Cháo trắng',
    nameEn: 'Plain rice porridge',
    category: 'rice_grain',
    per100g: n(45, 0.9, 9.8, 0.1, 0.1),
    dataQuality: 'high',
    sourceReference: USDA('cooked rice congee, high water content'),
    portions: P.soup(),
  },
  {
    externalId: 'vn-chao-ga',
    nameVi: 'Cháo gà',
    nameEn: 'Chicken rice porridge',
    category: 'rice_grain',
    per100g: n(68, 4.2, 9.4, 1.4, 0.2),
    dataQuality: 'medium',
    sourceReference: RECIPE('rice congee with shredded chicken and chicken stock'),
    portions: P.soup(),
  },
  {
    externalId: 'vn-banh-mi-khong',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Bánh mì không',
    nameEn: 'Plain Vietnamese baguette',
    category: 'bread',
    per100g: n(274, 8.6, 55.0, 1.6, 2.3),
    dataQuality: 'high',
    sourceReference: USDA('French/Vienna-style white bread'),
    portions: P.piece(80, '1 ổ'),
  },
  {
    externalId: 'vn-banh-mi-thit',
    nameVi: 'Bánh mì thịt',
    nameEn: 'Vietnamese pork baguette sandwich',
    category: 'street_food',
    per100g: n(248, 10.2, 30.5, 9.4, 1.9),
    dataQuality: 'medium',
    sourceReference: RECIPE('80 g baguette, 45 g cold cuts and pâté, mayonnaise, pickled carrot and daikon, coriander'),
    portions: P.piece(180, '1 ổ'),
  },
  {
    externalId: 'vn-banh-mi-trung',
    nameVi: 'Bánh mì trứng',
    nameEn: 'Egg baguette sandwich',
    category: 'breakfast',
    per100g: n(236, 9.6, 32.0, 8.2, 1.8),
    dataQuality: 'medium',
    sourceReference: RECIPE('80 g baguette, two fried eggs, chilli sauce and cucumber'),
    portions: P.piece(160, '1 ổ'),
  },
  {
    externalId: 'vn-banh-mi-cha-ca',
    nameVi: 'Bánh mì chả cá',
    nameEn: 'Fish cake baguette sandwich',
    category: 'street_food',
    per100g: n(242, 11.0, 31.0, 8.4, 1.8),
    dataQuality: 'medium',
    sourceReference: RECIPE('80 g baguette, 60 g fried fish cake, herbs and chilli sauce'),
    portions: P.piece(170, '1 ổ'),
  },
  {
    externalId: 'vn-banh-cuon',
    nameVi: 'Bánh cuốn',
    nameEn: 'Steamed rice rolls with pork and wood ear',
    category: 'breakfast',
    per100g: n(148, 5.6, 24.0, 3.4, 0.8),
    dataQuality: 'medium',
    sourceReference: RECIPE('steamed rice batter sheets filled with minced pork and wood ear, fried shallot, served with nước chấm'),
    portions: [{ label: '1 plate', labelVi: '1 đĩa', grams: 250, isDefault: true }],
  },
  {
    externalId: 'vn-banh-gio',
    nameVi: 'Bánh giò',
    nameEn: 'Pyramidal rice dumpling with pork',
    category: 'breakfast',
    per100g: n(163, 5.2, 24.5, 4.8, 0.7),
    dataQuality: 'medium',
    sourceReference: RECIPE('rice flour dough with minced pork, wood ear and shallot, steamed in banana leaf'),
    portions: P.piece(200, '1 cái'),
  },
  {
    externalId: 'vn-banh-chung',
    nameVi: 'Bánh chưng',
    nameEn: 'Square sticky rice cake with pork and mung bean',
    category: 'rice_grain',
    per100g: n(214, 6.4, 32.0, 6.6, 1.4),
    dataQuality: 'medium',
    sourceReference: RECIPE('glutinous rice, mung bean paste and fatty pork belly, boiled in dong leaf'),
    portions: [
      { label: '1 slice', labelVi: '1 miếng', grams: 120, isDefault: true },
      { label: 'quarter cake', labelVi: '1/4 cái', grams: 200 },
    ],
  },
  {
    externalId: 'vn-banh-tet',
    nameVi: 'Bánh tét',
    nameEn: 'Cylindrical sticky rice cake',
    category: 'rice_grain',
    per100g: n(210, 6.0, 32.5, 6.2, 1.3),
    dataQuality: 'medium',
    sourceReference: RECIPE('as bánh chưng, rolled rather than square'),
    portions: [{ label: '1 slice', labelVi: '1 khoanh', grams: 100, isDefault: true }],
  },
  {
    externalId: 'vn-khoai-lang-luoc',
    nameVi: 'Khoai lang luộc',
    nameEn: 'Boiled sweet potato',
    category: 'rice_grain',
    per100g: n(90, 2.0, 20.7, 0.2, 3.3),
    dataQuality: 'high',
    sourceReference: USDA('sweet potato, boiled without skin'),
    portions: P.wholeFruit(150),
  },
  {
    externalId: 'vn-khoai-tay-chien',
    nameVi: 'Khoai tây chiên',
    nameEn: 'French fries',
    category: 'snack',
    per100g: n(312, 3.4, 41.0, 15.0, 3.8),
    dataQuality: 'high',
    sourceReference: USDA('potatoes, french fried, deep fried'),
    portions: [{ label: '1 serving', labelVi: '1 phần', grams: 120, isDefault: true }],
  },
  {
    externalId: 'vn-bun-tuoi',
    // Curated default for the bare term (see foods.search_priority).
    searchPriority: 10,
    nameVi: 'Bún tươi',
    nameEn: 'Fresh rice vermicelli (plain)',
    category: 'noodle_dry',
    per100g: n(110, 1.9, 25.0, 0.2, 0.6),
    dataQuality: 'high',
    sourceReference: USDA('rice noodles, cooked'),
    portions: P.rice(),
  },
  {
    externalId: 'vn-banh-pho-tuoi',
    nameVi: 'Bánh phở tươi',
    nameEn: 'Fresh flat rice noodles (plain)',
    category: 'noodle_dry',
    per100g: n(112, 1.9, 25.4, 0.2, 0.6),
    dataQuality: 'high',
    sourceReference: USDA('rice noodles, cooked'),
    portions: P.rice(),
  },
  {
    externalId: 'vn-mien-dong',
    nameVi: 'Miến dong',
    nameEn: 'Glass noodles, cooked',
    category: 'noodle_dry',
    per100g: n(105, 0.1, 26.0, 0.0, 0.5),
    dataQuality: 'high',
    sourceReference: USDA('mung bean starch noodles, cooked'),
    portions: P.rice(),
  },
  {
    externalId: 'vn-mi-goi',
    nameVi: 'Mì gói',
    nameEn: 'Instant noodles, prepared',
    category: 'noodle_soup',
    per100g: n(139, 3.1, 18.8, 5.6, 0.9),
    dataQuality: 'medium',
    sourceReference: RECIPE('one 75 g fried instant noodle block with its seasoning, prepared with water'),
    portions: [{ label: '1 pack', labelVi: '1 gói', grams: 350, isDefault: true }],
  },
];
